"""empty message

Revision ID: 2dff01aa9453
Revises: 36b341ef1987
Create Date: 2023-01-14 14:46:03.238640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dff01aa9453'
down_revision = '36b341ef1987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('short_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker', 'short_name')
    # ### end Alembic commands ###
