"""empty message

Revision ID: 36b341ef1987
Revises: d2855955a50f
Create Date: 2023-01-14 14:35:43.316487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b341ef1987'
down_revision = 'd2855955a50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('name', sa.String(), nullable=True))
    op.add_column('ticker', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('ticker', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker', 'type')
    op.drop_column('ticker', 'full_name')
    op.drop_column('ticker', 'name')
    # ### end Alembic commands ###
