"""empty message

Revision ID: c41be3aa8f64
Revises: f21bd34e9616
Create Date: 2023-01-16 17:27:28.715929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c41be3aa8f64'
down_revision = 'f21bd34e9616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart', 'ownerSource',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chart', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chart', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chart', 'resolution',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chart', 'lastModified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('chart', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('drawingtemplate', 'ownerSource',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drawingtemplate', 'ownerId',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drawingtemplate', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drawingtemplate', 'tool',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drawingtemplate', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('industry', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('industry', 'enName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('studytemplate', 'ownerSource',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('studytemplate', 'ownerId',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('studytemplate', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('studytemplate', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ticker', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ticker', 'exchange',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ticker', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ticker', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ticker', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ticker', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticker', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticker', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticker', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticker', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticker', 'exchange',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticker', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('studytemplate', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('studytemplate', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('studytemplate', 'ownerId',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('studytemplate', 'ownerSource',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('industry', 'enName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('industry', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drawingtemplate', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('drawingtemplate', 'tool',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drawingtemplate', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drawingtemplate', 'ownerId',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drawingtemplate', 'ownerSource',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chart', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('chart', 'lastModified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('chart', 'resolution',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chart', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chart', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chart', 'ownerSource',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
