"""empty message

Revision ID: d2855955a50f
Revises: ef95937b7947
Create Date: 2023-01-14 14:26:55.846446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2855955a50f'
down_revision = 'ef95937b7947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticker_industry_id_fkey', 'ticker', type_='foreignkey')
    op.drop_column('ticker', 'shortName')
    op.drop_column('ticker', 'industry_id')
    op.drop_column('ticker', 'companyName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('companyName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ticker', sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ticker', sa.Column('shortName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('ticker_industry_id_fkey', 'ticker', 'industry', ['industry_id'], ['id'])
    # ### end Alembic commands ###
