"""empty message

Revision ID: d86aa89d65dc
Revises: 2dff01aa9453
Create Date: 2023-01-14 15:37:46.434229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86aa89d65dc'
down_revision = '2dff01aa9453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticker_ticker', table_name='ticker')
    op.create_index(op.f('ix_ticker_ticker'), 'ticker', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_ticker'), table_name='ticker')
    op.create_index('ix_ticker_ticker', 'ticker', ['ticker'], unique=False)
    # ### end Alembic commands ###
