"""empty message

Revision ID: ef95937b7947
Revises: cfe1dad99ff5
Create Date: 2023-01-08 07:15:35.707115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef95937b7947'
down_revision = 'cfe1dad99ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('enName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_id'), 'industry', ['id'], unique=False)
    op.create_table('ticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('shortName', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_id'), 'ticker', ['id'], unique=False)
    op.create_index(op.f('ix_ticker_ticker'), 'ticker', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_ticker'), table_name='ticker')
    op.drop_index(op.f('ix_ticker_id'), table_name='ticker')
    op.drop_table('ticker')
    op.drop_index(op.f('ix_industry_id'), table_name='industry')
    op.drop_table('industry')
    # ### end Alembic commands ###
